#!/usr/bin/env python3
"""Emit a named-family width/locality bound skeleton for B9."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from b9_local_hamiltonian_gap_lab import build_terms


LEAN_SOURCE = """-- B9 cluster-stabilizer named-family width/locality skeleton v0.1
-- Generated by tools/b9_named_family_width_locality_bounds.py
-- This file is a proof skeleton, not a proof-assistant checked theorem.

import Mathlib.Data.Real.Basic

namespace B9Cluster

structure SpectralSummary where
  gap : Real
  width : Real
  normalizedGap : Real
  locality : Nat

def RawGapAmplifies (before after : SpectralSummary) : Prop :=
  after.gap > before.gap

def NormalizedGapInvariant (before after : SpectralSummary) : Prop :=
  after.normalizedGap = before.normalizedGap

def LocalityPreserved (before after : SpectralSummary) : Prop :=
  after.locality = before.locality

theorem uniform_positive_scale_preserves_normalized_gap
    (gap width scale : Real)
    (before after : SpectralSummary)
    (hBefore : before.normalizedGap = gap / width)
    (hAfter : after.normalizedGap = (scale * gap) / (scale * width))
    (hRatio : (scale * gap) / (scale * width) = gap / width) :
    after.normalizedGap = before.normalizedGap := by
  rw [hAfter, hBefore, hRatio]

theorem uniform_scale_raw_gap_is_not_certificate
    (before after : SpectralSummary)
    (hRaw : RawGapAmplifies before after)
    (hInvariant : NormalizedGapInvariant before after) :
    ¬ (after.normalizedGap > before.normalizedGap) := by
  intro hImproves
  rw [hInvariant] at hImproves
  exact (lt_irrefl before.normalizedGap) hImproves

-- Named-family obligation: instantiate SpectralSummary with the open-boundary
-- cluster stabilizer Hamiltonian H_n and transformed Hamiltonian 1.35 * H_n.
-- The generated JSON/Markdown artifact checks the finite rows n = 4, 5, 6
-- and records the analytic assumptions to formalize next.
theorem cluster_stabilizer_open_uniform_reweight_obligation
    (n : Nat)
    (hN : 4 <= n)
    (before after : SpectralSummary)
    (hLocality : LocalityPreserved before after)
    (hRaw : RawGapAmplifies before after)
    (hInvariant : NormalizedGapInvariant before after) :
    after.locality = before.locality ∧
      ¬ (after.normalizedGap > before.normalizedGap) := by
  constructor
  · exact hLocality
  · exact uniform_scale_raw_gap_is_not_certificate before after hRaw hInvariant

end B9Cluster
"""


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def support_profile(model: str, qubits: int, interaction_scale: float, field_scale: float) -> dict:
    terms = build_terms(model, qubits)
    supports = [len(term["labels"]) for term in terms]
    scales = [interaction_scale if support >= 2 else field_scale for support in supports]
    return {
        "qubits": qubits,
        "term_count": len(terms),
        "supports": supports,
        "unique_supports": sorted(set(supports)),
        "scales": scales,
        "unique_scales": sorted(set(scales)),
        "max_support": max(supports),
        "all_terms_scaled_uniformly": len(set(scales)) == 1,
        "uniform_scale": scales[0] if len(set(scales)) == 1 else None,
    }


def lean_check_status(lean_file: Path) -> dict:
    executable = shutil.which("lean")
    lake = shutil.which("lake")
    if not executable and not lake:
        return {
            "proof_assistant_available": False,
            "proof_assistant_executable": None,
            "proof_assistant_checked": False,
            "proof_assistant_check_status": "lean_executable_not_found",
            "proof_assistant_check_detail": "No lean executable found on PATH.",
        }

    try:
        command = [lake, "env", "lean", str(lean_file)] if lake else [executable, str(lean_file)]
        completed = subprocess.run(
            command,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=20,
        )
    except Exception as exc:  # noqa: BLE001 - status artifact should keep the exact environment failure.
        return {
            "proof_assistant_available": True,
            "proof_assistant_executable": lake or executable,
            "proof_assistant_checked": False,
            "proof_assistant_check_status": "lean_check_exception",
            "proof_assistant_check_detail": str(exc),
        }

    detail = (completed.stdout + "\n" + completed.stderr).strip()
    return {
        "proof_assistant_available": True,
        "proof_assistant_executable": lake or executable,
        "proof_assistant_checked": completed.returncode == 0,
        "proof_assistant_check_status": "passed" if completed.returncode == 0 else "failed",
        "proof_assistant_return_code": completed.returncode,
        "proof_assistant_check_detail": detail[:2000],
    }


def validate_report(report: dict) -> list[str]:
    errors: list[str] = []
    if report.get("status") != "named_family_width_locality_bound_skeleton_not_checked_theorem":
        errors.append("status must identify named-family bound as an unchecked theorem skeleton")
    if report.get("method") != "b9_named_family_width_locality_bound_v0":
        errors.append("method mismatch")
    if report.get("named_family") != "cluster_stabilizer_open_uniform_reweight":
        errors.append("named family mismatch")
    if int(report.get("rows_matched", 0)) < 3:
        errors.append("expected at least three finite rows")
    if report.get("all_terms_scaled_uniformly") is not True:
        errors.append("all cluster-stabilizer terms should be uniformly scaled")
    if report.get("locality_bound_preserved") is not True:
        errors.append("locality bound should be preserved")
    if report.get("normalized_gap_invariant_under_uniform_scaling") is not True:
        errors.append("normalized gap invariance should be recorded")
    if report.get("raw_gap_amplifies") is not True:
        errors.append("raw gap amplification should be observed")
    if report.get("certificate_rejected") is not True:
        errors.append("uniform scaling certificate must be rejected")
    if report.get("formal_theorem_proved") is not False:
        errors.append("formal theorem proved must remain false")
    if report.get("explicit_not_quantum_pcp_proof") is not True:
        errors.append("must explicitly avoid Quantum PCP proof claims")
    if report.get("global_gap_amplification_impossibility_claimed") is not False:
        errors.append("must not claim global impossibility")
    if len(report.get("validation_errors", [])) != 0:
        errors.append("nested validation errors should be empty before finalization")
    return errors


def run(source_path: Path, lean_output: Path) -> dict:
    source = load_json(source_path)
    rows = [
        row
        for row in source.get("results", [])
        if row.get("model") == "cluster_stabilizer_open"
        and row.get("transformation") == "local_interaction_reweight_v0"
    ]
    qubits = sorted(row["qubits"] for row in rows)
    profiles = [support_profile("cluster_stabilizer_open", n_qubits, 1.35, 0.90) for n_qubits in qubits]
    all_uniform = bool(profiles) and all(profile["all_terms_scaled_uniformly"] for profile in profiles)
    observed_scales = sorted({profile["uniform_scale"] for profile in profiles if profile["uniform_scale"] is not None})
    max_locality = max(profile["max_support"] for profile in profiles) if profiles else None
    normalized_ratios = [row["normalized_gap_ratio"] for row in rows]
    gap_ratios = [row["gap_ratio"] for row in rows]
    ground_overlaps = [row["ground_state_overlap"] for row in rows]
    lean_output.parent.mkdir(parents=True, exist_ok=True)
    lean_output.write_text(LEAN_SOURCE, encoding="utf-8")
    lean_status = lean_check_status(lean_output)

    report = {
        "benchmark_id": "B9",
        "problem_id": 17,
        "title": "B9 cluster-stabilizer named-family width/locality bound skeleton",
        "version": "0.1",
        "last_updated": "2026-07-15",
        "status": "named_family_width_locality_bound_skeleton_not_checked_theorem",
        "method": "b9_named_family_width_locality_bound_v0",
        "source_result": str(source_path),
        "source_method": source.get("method"),
        "named_family": "cluster_stabilizer_open_uniform_reweight",
        "model": "cluster_stabilizer_open",
        "transformation": "local_interaction_reweight_v0",
        "qubits": qubits,
        "rows_matched": len(rows),
        "scaling_factor": 1.35,
        "observed_uniform_scales": observed_scales,
        "support_profiles": profiles,
        "all_terms_scaled_uniformly": all_uniform,
        "max_locality": max_locality,
        "locality_bound_preserved": max_locality == 3 and all_uniform,
        "ground_space_preserved_by_uniform_scaling": bool(ground_overlaps) and min(ground_overlaps) >= 0.999999,
        "normalized_gap_ratios": normalized_ratios,
        "max_abs_normalized_gap_ratio_error_from_one": max(abs(value - 1.0) for value in normalized_ratios)
        if normalized_ratios
        else None,
        "normalized_gap_invariant_under_uniform_scaling": bool(normalized_ratios)
        and max(abs(value - 1.0) for value in normalized_ratios) <= 1e-12,
        "gap_ratios": gap_ratios,
        "raw_gap_amplifies": bool(gap_ratios) and min(gap_ratios) > 1.05,
        "certificate_rejected": True,
        "rejection_reason": "Raw spectral gap growth is exactly global positive energy rescaling; spectral width scales by the same factor, so normalized gap does not improve.",
        "analytic_bound_statement": [
            "For the open-boundary cluster stabilizer family, every generated term has support size 2 or 3.",
            "The B9 local_interaction_reweight_v0 transformation multiplies every support>=2 term by 1.35.",
            "Therefore H'_n = 1.35 * H_n for the generated family rows.",
            "Positive uniform scaling preserves eigenvectors and scales both spectral gap and spectral width by 1.35.",
            "The normalized gap gap(H)/width(H) is invariant, while max locality remains 3.",
        ],
        "lean_skeleton_output": str(lean_output),
        **lean_status,
        "formal_theorem_proved": False,
        "explicit_not_quantum_pcp_proof": True,
        "global_gap_amplification_impossibility_claimed": False,
        "claim_boundary": [
            "Supported: a named-family analytic skeleton explaining why the B9 v0 cluster-stabilizer local reweight rows are only uniform energy rescaling.",
            "Supported: finite rows n=4,5,6 match the symbolic locality/width story.",
            "Not supported: proof-assistant checked theorem, Quantum PCP proof, NLTS theorem, or global gap-amplification no-go theorem.",
        ],
        "remaining_steps_to_full_resolution": [
            "Formalize the parameterized open-boundary cluster stabilizer Hamiltonian in an actual Lean/mathlib project.",
            "Prove the support-size and uniform-scaling lemmas over all n >= 4.",
            "Prove spectral gap, spectral width, and normalized-gap scaling for positive scalar multiplication of self-adjoint matrices.",
            "Connect the finite JSON rows to generated certificates rather than manual inspection.",
            "Generalize from this rejected uniform-scaling family to nontrivial locality-preserving transformations or prove a narrower no-go theorem.",
        ],
    }
    report["validation_errors"] = validate_report({**report, "validation_errors": []})
    return report


def markdown(report: dict) -> str:
    lines = [
        "# B9 Named-Family Width/Locality Bound Skeleton v0.1",
        "",
        "Last updated: 2026-06-17",
        "",
        f"Status: **{report['status']}**",
        "",
        "## Summary",
        "",
        f"- Named family: `{report['named_family']}`",
        f"- Source method: {report['source_method']}",
        f"- Rows matched: {report['rows_matched']} for qubits {report['qubits']}",
        f"- Scaling factor: {report['scaling_factor']}",
        f"- Max locality: {report['max_locality']}",
        f"- Locality bound preserved: {report['locality_bound_preserved']}",
        f"- Raw gap amplifies: {report['raw_gap_amplifies']}",
        f"- Normalized gap invariant: {report['normalized_gap_invariant_under_uniform_scaling']}",
        f"- Certificate rejected: {report['certificate_rejected']}",
        f"- Proof assistant checked: {report['proof_assistant_checked']}",
        f"- Proof assistant status: {report['proof_assistant_check_status']}",
        f"- Formal theorem proved: {report['formal_theorem_proved']}",
        f"- Explicitly not Quantum PCP proof: {report['explicit_not_quantum_pcp_proof']}",
        f"- Global impossibility claimed: {report['global_gap_amplification_impossibility_claimed']}",
        f"- Validation errors: {len(report['validation_errors'])}",
        "",
        "## Analytic Bound Statement",
        "",
    ]
    lines.extend(f"- {item}" for item in report["analytic_bound_statement"])
    lines.extend(["", "## Finite Row Checks", ""])
    for profile in report["support_profiles"]:
        lines.append(
            "- n={qubits}: term_count={term_count}, supports={unique_supports}, "
            "unique_scales={unique_scales}, max_support={max_support}".format(**profile)
        )
    lines.extend(["", "## Rejection Reason", "", report["rejection_reason"], ""])
    lines.extend(["## Claim Boundary", ""])
    lines.extend(f"- {item}" for item in report["claim_boundary"])
    lines.extend(["", "## Remaining Steps", ""])
    lines.extend(f"- {item}" for item in report["remaining_steps_to_full_resolution"])
    if report.get("proof_assistant_check_detail"):
        lines.extend(["", "## Proof-Check Environment Note", "", "```text", report["proof_assistant_check_detail"], "```"])
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("results/B9_local_hamiltonian_gap_lab_v0.json"))
    parser.add_argument(
        "--lean-output",
        type=Path,
        default=Path("research/proof_skeletons/B9_cluster_stabilizer_width_locality_bound.lean"),
    )
    parser.add_argument("--json-output", type=Path, default=Path("results/B9_named_family_width_locality_bounds_v0.json"))
    parser.add_argument("--markdown-output", type=Path, default=Path("research/B9_named_family_width_locality_bounds.md"))
    parser.add_argument("--pretty", action="store_true")
    args = parser.parse_args()

    report = run(args.source, args.lean_output)
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_output.write_text(markdown(report), encoding="utf-8")
    if args.pretty:
        print(
            json.dumps(
                {
                    "status": report["status"],
                    "named_family": report["named_family"],
                    "rows_matched": report["rows_matched"],
                    "locality_bound_preserved": report["locality_bound_preserved"],
                    "normalized_gap_invariant_under_uniform_scaling": report[
                        "normalized_gap_invariant_under_uniform_scaling"
                    ],
                    "proof_assistant_checked": report["proof_assistant_checked"],
                    "proof_assistant_check_status": report["proof_assistant_check_status"],
                    "validation_error_count": len(report["validation_errors"]),
                },
                indent=2,
                sort_keys=True,
            )
        )
    return 1 if report["validation_errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
